---
- name: deploy RRE on EC2
  hosts: all
  remote_user: ubuntu
  become_user: ubuntu
  tasks:
    - name: "Add nodejs apt key"
      become: yes
      become_user: root
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: "Add nodejs 16.x ppa for apt repo"
      become: yes
      become_user: root
      apt_repository:
        repo: deb https://deb.nodesource.com/node_16.x focal main
        update_cache: yes

    - name: Install nodejs
      become: yes
      become_user: root
      ansible.builtin.apt:
        name: nodejs

    - name: get latest github repo
      git:
        repo: https://github.com/transitmatters/regional-rail-explorer.git
        dest: /home/ubuntu/regional-rail-explorer
        force: yes

    - name: copy systemd service file
      copy:
        src: systemd.conf
        dest: /etc/systemd/system/regional-rail-explorer.service
      become: yes
      become_user: root

    - name: Install nginx
      become: yes
      become_user: root
      ansible.builtin.apt:
        name: nginx

    - name: copy nginx config file
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-enabled/default
      become: yes
      become_user: root

    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
        daemon_reload: yes
      become: yes
      become_user: root

    - name: install app dependencies
      shell: npm ci
      args:
        chdir: /home/ubuntu/regional-rail-explorer

    - name: build application
      shell: npm run build
      args:
        chdir: /home/ubuntu/regional-rail-explorer

    - name: restart service
      shell: systemctl restart regional-rail-explorer
      become: yes
      become_user: root
